# Generated by Django 5.0.4 on 2026-02-25 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasanaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('total_participants', models.IntegerField(verbose_name='Total Participants')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Amount')),
                ('draws_per_month', models.IntegerField(default=2, verbose_name='Draws Per Month')),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pasanaku',
                'verbose_name_plural': 'Pasanakus',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(default=False)),
                ('winning_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='participants.participant')),
                ('pasanaku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='pasanaku.pasanaku')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'ordering': ['created_at'],
                'unique_together': {('pasanaku', 'participant')},
            },
        ),
    ]
