# Generated by Django 5.0.4 on 2026-02-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasanaku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasanaku',
            name='rotation_angle',
            field=models.FloatField(default=0.0, verbose_name='Rotation Angle'),
        ),
    ]
