# Generated by Django 5.0.4 on 2026-03-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasanaku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_temporarily_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pasanaku',
            name='current_pre_draw_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Pre Draw Count'),
        ),
        migrations.AddField(
            model_name='pasanaku',
            name='draws_before_winner',
            field=models.PositiveIntegerField(default=1, verbose_name='Draws Before Winner'),
        ),
    ]
