# Generated by Django 6.0.2 on 2026-02-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasanaku', '0002_participation'),
        ('pasanaku', '0002_pasanaku_rotation_angle'),
    ]

    operations = [
    ]
