# Generated by Django 5.0.4 on 2026-02-25 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasanaku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_number', models.IntegerField()),
                ('draw_date', models.DateTimeField(auto_now_add=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='pasanaku.participation')),
                ('pasanaku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='pasanaku.pasanaku')),
            ],
            options={
                'verbose_name': 'Draw',
                'verbose_name_plural': 'Draws',
                'ordering': ['draw_number'],
                'unique_together': {('pasanaku', 'draw_number')},
            },
        ),
    ]
